# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a637a249e95bf37f57d5975fd3c444500ec96342af17269226033db20cbb31ae09a5bff963b09e3682620cc239353c5993dc44e2de38f774d76ab9ef4b73ff8

test:
  secret_key_base: 85593fd506fb58917e8c3fdbdcb99b5b789f2a55bbfc2f07f6846b8d764cb34fbfe5c67abfed905fbe5fb204b524154911500f314353543bc9f386cea0e79c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
